name: "Set up CI in projects templated with blakeNaccarato/copier-python"
description: "Updates the project template and composes `pyproject.toml`."
inputs:
  python-version:
    description: "Python version to use."
    required: true
    default: "3.11"
  install-project:
    description: "Whether to install the project dependencies."
    required: false
    default: "true"
runs:
  using: "composite"
  steps:
    - uses: "actions/checkout@v3.5.3"
      with:
        submodules: true
    - uses: "actions/setup-python@v4.6.1"
      with:
        python-version: ${{ inputs.python-version }}
        cache: "pip"
        cache-dependency-path: |
          requirements.txt
          .tools/requirements/requirements*.txt
    - name: "Install dependencies, bump template, compose `pyproject.toml`."
      shell: "pwsh"
      run: |-
        python -m pip install --upgrade pip
        pip install --upgrade setuptools wheel
        pip install --requirement .tools/requirements/requirements_ci.txt
        copier update --defaults --vcs-ref $(git rev-parse HEAD:template)
        python .tools/scripts/compose_pyproject.py
    - name: "Install the project and its dependencies."
      if: ${{ inputs.install-project }}
      shell: "pwsh"
      run: |-
        pip install --no-deps .
        pip install --upgrade --requirement 'requirements.txt'
