name: "hello"
description: "hello"
inputs:
  python-version:
    description: "Python version to use."
    required: true
    default: "3.11"
  install-project:
    description: "Install the project."
    required: false
    default: "true"
runs:
  using: "composite"
  steps:
    - uses: "actions/checkout@v3"
      with:
        submodules: true
    - uses: "actions/setup-python@v4"
      with:
        python-version: ${{ inputs.python-version }}
        cache: "pip"
        cache-dependency-path: |
          requirements.txt
          .tools/requirements/requirements*.txt
    - run: |-
        pip install -U pip setuptools wheel
        pip install -r .tools/requirements/requirements_cicd.txt
      shell: "bash"
    - if: ${{ inputs.install-project }}
      run: pip install .
      shell: "bash"
