name: "Set up CI in projects templated with blakeNaccarato/copier-python"
description: "Prepare to run CI."
inputs:
  python-version:
    description: "Python version to use."
    required: true
    default: "3.11"
  latest-pins:
    description: "Whether to install the latest pin on dependencies."
    required: false
    default: "true"
  install-project:
    description: "Whether to install the project dependencies."
    required: false
    default: "true"
runs:
  using: "composite"
  steps:
    - uses: "actions/checkout@v4.1.1"
      with:
        submodules: true
    - uses: "actions/setup-python@v4.7.1"
      with:
        python-version: "${{ inputs.python-version }}"
        cache: "pip"
        cache-dependency-path: ".tools/requirements/requirements*.txt"
    - name: "Install core dependencies."
      shell: "pwsh"
      run: |-
        python -m pip install --requirement '.tools/requirements/requirements_core.txt'
    - name: "Update the template if necessary."
      shell: "pwsh"
      run: "copier update --defaults --vcs-ref $(git rev-parse HEAD:submodules/template)"
    - name: "Run core update script."
      shell: "pwsh"
      run: "python .tools/scripts/core_update.py"
    - name: "Install project with the latest supported requirements."
      if: "${{ inputs.install-project && inputs.latest-pins }}"
      shell: "pwsh"
      run: |-
        python -m pip install --no-deps . --requirement '.tools/requirements/requirements_nodeps.txt'
        python -m pip install --requirement '.tools/requirements/requirements.txt' --requirement '.tools/requirements/requirements_ci.txt'
    - name: "Install project."
      if: "${{ inputs.install-project && !inputs.latest-pins }}"
      shell: "pwsh"
      run: |-
        python -m pip install --no-deps --requirement '.tools/requirements/requirements_nodeps.txt'
        python -m pip install . --requirement '.tools/requirements/requirements_ci.txt'
    - name: "Install developer dependencies."
      if: "${{ !inputs.install-project }}"
      shell: "pwsh"
      run: |-
        python -m pip install --requirement '.tools/requirements/requirements_ci.txt'
