name: "hello"
description: "hello"
runs:
  using: "composite"
  steps:
    - uses: "actions/checkout@v3"
      with:
        submodules: true
    - uses: "actions/setup-python@v4"
      with:
        python-version: "3.10"
    - run: ".tools/scripts/cicd_setup.sh"
      shell: "bash"
